using NumbersInEnglish.ApplicationContextDB;
using NumbersInEnglish.Models;
using System.Collections.Generic;

namespace NumbersInEnglish.Helpers
{
    public static class InformationData
    {
        public static void DataDefault()
        {
            var _dbCcontext = new ApplicationContext_DB();

            var numbers = new List<Numbers>
            {
                new Numbers { IdNumber = 1, Number = 1, Traduction = "ONE" },
                new Numbers { IdNumber = 2, Number = 2, Traduction = "TWO" },
                new Numbers { IdNumber = 3, Number = 3, Traduction = "THREE" },
                new Numbers { IdNumber = 4, Number = 4, Traduction = "FOUR" },
                new Numbers { IdNumber = 5, Number = 5, Traduction = "FIVE" },
                new Numbers { IdNumber = 6, Number = 6, Traduction = "SIX" },
                new Numbers { IdNumber = 7, Number = 7, Traduction = "SEVEN" },
                new Numbers { IdNumber = 8, Number = 8, Traduction = "EIGHT" },
                new Numbers { IdNumber = 9, Number = 9, Traduction = "NINE" },
                new Numbers { IdNumber = 10, Number = 10, Traduction = "TEN" },
                new Numbers { IdNumber = 11, Number = 11, Traduction = "ELEVEN" },
                new Numbers { IdNumber = 12, Number = 12, Traduction = "TWELVE" },
                new Numbers { IdNumber = 13, Number = 13, Traduction = "THIRTEEN" },
                new Numbers { IdNumber = 14, Number = 14, Traduction = "FOURTEEN" },
                new Numbers { IdNumber = 15, Number = 15, Traduction = "FIFTEEN" },
                new Numbers { IdNumber = 16, Number = 16, Traduction = "SIXTEEN" },
                new Numbers { IdNumber = 17, Number = 17, Traduction = "SEVENTEEN" },
                new Numbers { IdNumber = 18, Number = 18, Traduction = "EIGHTEEN" },
                new Numbers { IdNumber = 19, Number = 19, Traduction = "NINETEEN" },
                new Numbers { IdNumber = 20, Number = 20, Traduction = "TWENTY" },
                new Numbers { IdNumber = 21, Number = 21, Traduction = "TWENTY ONE" },
                new Numbers { IdNumber = 22, Number = 22, Traduction = "TWENTY TWO" },
                new Numbers { IdNumber = 23, Number = 23, Traduction = "TWENTY THREE" },
                new Numbers { IdNumber = 24, Number = 24, Traduction = "TWENTY FOUR" },
                new Numbers { IdNumber = 25, Number = 25, Traduction = "TWENTY FIVE" },
                new Numbers { IdNumber = 26, Number = 26, Traduction = "TWENTY SIX" },
                new Numbers { IdNumber = 27, Number = 27, Traduction = "TWENTY SEVEN" },
                new Numbers { IdNumber = 28, Number = 28, Traduction = "TWENTY EIGHT" },
                new Numbers { IdNumber = 29, Number = 29, Traduction = "TWENTY NINE" },
                new Numbers { IdNumber = 30, Number = 30, Traduction = "THIRTY" },
                new Numbers { IdNumber = 31, Number = 31, Traduction = "THIRTY ONE" },
                new Numbers { IdNumber = 32, Number = 32, Traduction = "THIRTY TWO" },
                new Numbers { IdNumber = 33, Number = 33, Traduction = "THIRTY THREE" },
                new Numbers { IdNumber = 34, Number = 34, Traduction = "THIRTY FOUR" },
                new Numbers { IdNumber = 35, Number = 35, Traduction = "THIRTY FIVE" },
                new Numbers { IdNumber = 36, Number = 36, Traduction = "THIRTY SIX" },
                new Numbers { IdNumber = 37, Number = 37, Traduction = "THIRTY SEVEN" },
                new Numbers { IdNumber = 38, Number = 38, Traduction = "THIRTY EIGHT" },
                new Numbers { IdNumber = 39, Number = 39, Traduction = "THIRTY NINE" },
                new Numbers { IdNumber = 40, Number = 40, Traduction = "FORTY" },
                new Numbers { IdNumber = 41, Number = 41, Traduction = "FORTY ONE" },
                new Numbers { IdNumber = 42, Number = 42, Traduction = "FORTY TWO" },
                new Numbers { IdNumber = 43, Number = 43, Traduction = "FORTY THREE" },
                new Numbers { IdNumber = 44, Number = 44, Traduction = "FORTY FOUR" },
                new Numbers { IdNumber = 45, Number = 45, Traduction = "FORTY FIVE" },
                new Numbers { IdNumber = 46, Number = 46, Traduction = "FORTY SIX" },
                new Numbers { IdNumber = 47, Number = 47, Traduction = "FORTY SEVEN" },
                new Numbers { IdNumber = 48, Number = 48, Traduction = "FORTY EIGHT" },
                new Numbers { IdNumber = 49, Number = 49, Traduction = "FORTY NINE" },
                new Numbers { IdNumber = 50, Number = 50, Traduction = "FIFTY" },
                new Numbers { IdNumber = 51, Number = 51, Traduction = "FIFTY ONE" },
                new Numbers { IdNumber = 52, Number = 52, Traduction = "FIFTY TWO" },
                new Numbers { IdNumber = 53, Number = 53, Traduction = "FIFTY THREE" },
                new Numbers { IdNumber = 54, Number = 54, Traduction = "FIFTY FOUR" },
                new Numbers { IdNumber = 55, Number = 55, Traduction = "FIFTY FIVE" },
                new Numbers { IdNumber = 56, Number = 56, Traduction = "FIFTY SIX" },
                new Numbers { IdNumber = 57, Number = 57, Traduction = "FIFTY SEVEN" },
                new Numbers { IdNumber = 58, Number = 58, Traduction = "FIFTY EIGHT" },
                new Numbers { IdNumber = 59, Number = 59, Traduction = "FIFTY NINE" },
                new Numbers { IdNumber = 60, Number = 60, Traduction = "SIXTY" },
                new Numbers { IdNumber = 61, Number = 61, Traduction = "SIXTY ONE" },
                new Numbers { IdNumber = 62, Number = 62, Traduction = "SIXTY TWO" },
                new Numbers { IdNumber = 63, Number = 63, Traduction = "SIXTY THREE" },
                new Numbers { IdNumber = 64, Number = 64, Traduction = "SIXTY FOUR" },
                new Numbers { IdNumber = 65, Number = 65, Traduction = "SIXTY FIVE" },
                new Numbers { IdNumber = 66, Number = 66, Traduction = "SIXTY SIX" },
                new Numbers { IdNumber = 67, Number = 67, Traduction = "SIXTY SEVEN" },
                new Numbers { IdNumber = 68, Number = 68, Traduction = "SIXTY EIGHT" },
                new Numbers { IdNumber = 69, Number = 69, Traduction = "SIXTY NINE" },
                new Numbers { IdNumber = 70, Number = 70, Traduction = "SEVENTY" },
                new Numbers { IdNumber = 71, Number = 71, Traduction = "SEVENTY ONE" },
                new Numbers { IdNumber = 72, Number = 72, Traduction = "SEVENTY TWO" },
                new Numbers { IdNumber = 73, Number = 73, Traduction = "SEVENTY THREE" },
                new Numbers { IdNumber = 74, Number = 74, Traduction = "SEVENTY FOUR" },
                new Numbers { IdNumber = 75, Number = 75, Traduction = "SEVENTY FIVE" },
                new Numbers { IdNumber = 76, Number = 76, Traduction = "SEVENTY SIX" },
                new Numbers { IdNumber = 77, Number = 77, Traduction = "SEVENTY SEVEN" },
                new Numbers { IdNumber = 78, Number = 78, Traduction = "SEVENTY EIGHT" },
                new Numbers { IdNumber = 79, Number = 79, Traduction = "SEVENTY NINE" },
                new Numbers { IdNumber = 80, Number = 80, Traduction = "EIGHTY" },
                new Numbers { IdNumber = 81, Number = 81, Traduction = "EIGHTY ONE" },
                new Numbers { IdNumber = 82, Number = 82, Traduction = "EIGHTY TWO" },
                new Numbers { IdNumber = 83, Number = 83, Traduction = "EIGHTY THREE" },
                new Numbers { IdNumber = 84, Number = 84, Traduction = "EIGHTY FOUR" },
                new Numbers { IdNumber = 85, Number = 85, Traduction = "EIGHTY FIVE" },
                new Numbers { IdNumber = 86, Number = 86, Traduction = "EIGHTY SIX" },
                new Numbers { IdNumber = 87, Number = 87, Traduction = "EIGHTY SEVEN" },
                new Numbers { IdNumber = 88, Number = 88, Traduction = "EIGHTY EIGHT" },
                new Numbers { IdNumber = 89, Number = 89, Traduction = "EIGHTY NINE" },
                new Numbers { IdNumber = 90, Number = 90, Traduction = "NINETY" },
                new Numbers { IdNumber = 91, Number = 91, Traduction = "NINETY ONE" },
                new Numbers { IdNumber = 92, Number = 92, Traduction = "NINETY TWO" },
                new Numbers { IdNumber = 93, Number = 93, Traduction = "NINETY THREE" },
                new Numbers { IdNumber = 94, Number = 94, Traduction = "NINETY FOUR" },
                new Numbers { IdNumber = 95, Number = 95, Traduction = "NINETY FIVE" },
                new Numbers { IdNumber = 96, Number = 96, Traduction = "NINETY SIX" },
                new Numbers { IdNumber = 97, Number = 97, Traduction = "NINETY SEVEN" },
                new Numbers { IdNumber = 98, Number = 98, Traduction = "NINETY EIGHT" },
                new Numbers { IdNumber = 99, Number = 99, Traduction = "NINETY NINE" },
                new Numbers { IdNumber = 100, Number = 100, Traduction = "ONE HUNDRED" },
            };

            _dbCcontext.AddRange(numbers);
            _dbCcontext.SaveChanges();
        }
    }
}