using NumbersInEnglish.ApplicationContextDB;
using NumbersInEnglish.Models;
using System.Collections.Generic;

namespace NumbersInEnglish.Helpers
{
    public static class InformationData
    {
        public static void DataDefault()
        {
            var _dbCcontext = new ApplicationContext_DB();

            var numbers = new List<Numbers>
            {
                new Numbers { IdNumber = 1, Number = 1, Traduction = "ONE" },
                new Numbers { IdNumber = 2, Number = 2, Traduction = "TWO" },
                new Numbers { IdNumber = 3, Number = 3, Traduction = "THREE" },
                new Numbers { IdNumber = 4, Number = 4, Traduction = "FOUR" },
                new Numbers { IdNumber = 5, Number = 5, Traduction = "FIVE" },
                new Numbers { IdNumber = 6, Number = 6, Traduction = "SIX" },
                new Numbers { IdNumber = 7, Number = 7, Traduction = "SEVEN" },
                new Numbers { IdNumber = 8, Number = 8, Traduction = "EIGHT" },
                new Numbers { IdNumber = 9, Number = 9, Traduction = "NINE" },
                new Numbers { IdNumber = 10, Number = 10, Traduction = "TEN" },
                new Numbers { IdNumber = 11, Number = 11, Traduction = "ELEVEN" },
                new Numbers { IdNumber = 12, Number = 12, Traduction = "TWELVE" },
                new Numbers { IdNumber = 13, Number = 13, Traduction = "THIRTEEN" },
                new Numbers { IdNumber = 14, Number = 14, Traduction = "FOURTEEN" },
                new Numbers { IdNumber = 15, Number = 15, Traduction = "FIFTEEN" },
                new Numbers { IdNumber = 16, Number = 16, Traduction = "SIXTEEN" },
                new Numbers { IdNumber = 17, Number = 17, Traduction = "SEVENTEEN" },
                new Numbers { IdNumber = 18, Number = 18, Traduction = "EIGHTEEN" },
                new Numbers { IdNumber = 19, Number = 19, Traduction = "NINETEEN" },
                new Numbers { IdNumber = 20, Number = 20, Traduction = "TWENTY" },
                new Numbers { IdNumber = 21, Number = 21, Traduction = "TWENTY ONE" },
                new Numbers { IdNumber = 22, Number = 22, Traduction = "TWENTY TWO" },
                new Numbers { IdNumber = 23, Number = 23, Traduction = "TWENTY THREE" },
                new Numbers { IdNumber = 24, Number = 24, Traduction = "TWENTY FOUR" },
                new Numbers { IdNumber = 25, Number = 25, Traduction = "TWENTY FIVE" },
                new Numbers { IdNumber = 26, Number = 26, Traduction = "TWENTY SIX" },
                new Numbers { IdNumber = 27, Number = 27, Traduction = "TWENTY SEVEN" },
                new Numbers { IdNumber = 28, Number = 28, Traduction = "TWENTY EIGHT" },
                new Numbers { IdNumber = 29, Number = 29, Traduction = "TWENTY NINE" },
                new Numbers { IdNumber = 30, Number = 30, Traduction = "THIRTY" },
                new Numbers { IdNumber = 31, Number = 31, Traduction = "THIRTY ONE" },
                new Numbers { IdNumber = 32, Number = 32, Traduction = "THIRTY TWO" },
                new Numbers { IdNumber = 33, Number = 33, Traduction = "THIRTY THREE" },
                new Numbers { IdNumber = 34, Number = 34, Traduction = "THIRTY FOUR" },
                new Numbers { IdNumber = 35, Number = 35, Traduction = "THIRTY FIVE" },
                new Numbers { IdNumber = 36, Number = 36, Traduction = "THIRTY SIX" },
                new Numbers { IdNumber = 37, Number = 37, Traduction = "THIRTY SEVEN" },
                new Numbers { IdNumber = 38, Number = 38, Traduction = "THIRTY EIGHT" },
                new Numbers { IdNumber = 39, Number = 39, Traduction = "THIRTY NINE" },
                new Numbers { IdNumber = 40, Number = 40, Traduction = "FORTY" },
                new Numbers { IdNumber = 41, Number = 41, Traduction = "FORTY ONE" },
                new Numbers { IdNumber = 42, Number = 42, Traduction = "FORTY TWO" },
                new Numbers { IdNumber = 43, Number = 43, Traduction = "FORTY THREE" },
                new Numbers { IdNumber = 44, Number = 44, Traduction = "FORTY FOUR" },
                new Numbers { IdNumber = 45, Number = 45, Traduction = "FORTY FIVE" },
                new Numbers { IdNumber = 46, Number = 46, Traduction = "FORTY SIX" },
                new Numbers { IdNumber = 47, Number = 47, Traduction = "FORTY SEVEN" },
                new Numbers { IdNumber = 48, Number = 48, Traduction = "FORTY EIGHT" },
                new Numbers { IdNumber = 49, Number = 49, Traduction = "FORTY NINE" },
                new Numbers { IdNumber = 50, Number = 50, Traduction = "FIFTY" },
                new Numbers { IdNumber = 51, Number = 51, Traduction = "FIFTY ONE" },
                new Numbers { IdNumber = 52, Number = 52, Traduction = "FIFTY TWO" },
                new Numbers { IdNumber = 53, Number = 53, Traduction = "FIFTY THREE" },
                new Numbers { IdNumber = 54, Number = 54, Traduction = "FIFTY FOUR" },
                new Numbers { IdNumber = 55, Number = 55, Traduction = "FIFTY FIVE" },
                new Numbers { IdNumber = 56, Number = 56, Traduction = "FIFTY SIX" },
                new Numbers { IdNumber = 57, Number = 57, Traduction = "FIFTY SEVEN" },
                new Numbers { IdNumber = 58, Number = 58, Traduction = "FIFTY EIGHT" },
                new Numbers { IdNumber = 59, Number = 59, Traduction = "FIFTY NINE" },
                new Numbers { IdNumber = 60, Number = 60, Traduction = "SIXTY" },
                new Numbers { IdNumber = 61, Number = 61, Traduction = "SIXTY ONE" },
                new Numbers { IdNumber = 62, Number = 62, Traduction = "SIXTY TWO" },
                new Numbers { IdNumber = 63, Number = 63, Traduction = "SIXTY THREE" },
                new Numbers { IdNumber = 64, Number = 64, Traduction = "SIXTY FOUR" },
                new Numbers { IdNumber = 65, Number = 65, Traduction = "SIXTY FIVE" },
                new Numbers { IdNumber = 66, Number = 66, Traduction = "SIXTY SIX" },
                new Numbers { IdNumber = 67, Number = 67, Traduction = "SIXTY SEVEN" },
                new Numbers { IdNumber = 68, Number = 68, Traduction = "SIXTY EIGHT" },
                new Numbers { IdNumber = 69, Number = 69, Traduction = "SIXTY NINE" },
                new Numbers { IdNumber = 70, Number = 70, Traduction = "SEVENTY" },
                new Numbers { IdNumber = 71, Number = 71, Traduction = "SEVENTY ONE" },
                new Numbers { IdNumber = 72, Number = 72, Traduction = "SEVENTY TWO" },
                new Numbers { IdNumber = 73, Number = 73, Traduction = "SEVENTY THREE" },
                new Numbers { IdNumber = 74, Number = 74, Traduction = "SEVENTY FOUR" },
                new Numbers { IdNumber = 75, Number = 75, Traduction = "SEVENTY FIVE" },
                new Numbers { IdNumber = 76, Number = 76, Traduction = "SEVENTY SIX" },
                new Numbers { IdNumber = 77, Number = 77, Traduction = "SEVENTY SEVEN" },
                new Numbers { IdNumber = 78, Number = 78, Traduction = "SEVENTY EIGHT" },
                new Numbers { IdNumber = 79, Number = 79, Traduction = "SEVENTY NINE" },
                new Numbers { IdNumber = 80, Number = 80, Traduction = "EIGHTY" },
                new Numbers { IdNumber = 81, Number = 81, Traduction = "EIGHTY ONE" },
                new Numbers { IdNumber = 82, Number = 82, Traduction = "EIGHTY TWO" },
                new Numbers { IdNumber = 83, Number = 83, Traduction = "EIGHTY THREE" },
                new Numbers { IdNumber = 84, Number = 84, Traduction = "EIGHTY FOUR" },
                new Numbers { IdNumber = 85, Number = 85, Traduction = "EIGHTY FIVE" },
                new Numbers { IdNumber = 86, Number = 86, Traduction = "EIGHTY SIX" },
                new Numbers { IdNumber = 87, Number = 87, Traduction = "EIGHTY SEVEN" },
                new Numbers { IdNumber = 88, Number = 88, Traduction = "EIGHTY EIGHT" },
                new Numbers { IdNumber = 89, Number = 89, Traduction = "EIGHTY NINE" },
                new Numbers { IdNumber = 90, Number = 90, Traduction = "NINETY" },
                new Numbers { IdNumber = 91, Number = 91, Traduction = "NINETY ONE" },
                new Numbers { IdNumber = 92, Number = 92, Traduction = "NINETY TWO" },
                new Numbers { IdNumber = 93, Number = 93, Traduction = "NINETY THREE" },
                new Numbers { IdNumber = 94, Number = 94, Traduction = "NINETY FOUR" },
                new Numbers { IdNumber = 95, Number = 95, Traduction = "NINETY FIVE" },
                new Numbers { IdNumber = 96, Number = 96, Traduction = "NINETY SIX" },
                new Numbers { IdNumber = 97, Number = 97, Traduction = "NINETY SEVEN" },
                new Numbers { IdNumber = 98, Number = 98, Traduction = "NINETY EIGHT" },
                new Numbers { IdNumber = 99, Number = 99, Traduction = "NINETY NINE" },
                new Numbers { IdNumber = 100, Number = 100, Traduction = "ONE HUNDRED" },
                new Numbers { IdNumber = 101, Number = 101, Traduction = "ONE HUNDRED ONE" },
                new Numbers { IdNumber = 102, Number = 102, Traduction = "ONE HUNDRED TWO" },
                new Numbers { IdNumber = 103, Number = 103, Traduction = "ONE HUNDRED THREE" },
                new Numbers { IdNumber = 104, Number = 104, Traduction = "ONE HUNDRED FOUR" },
                new Numbers { IdNumber = 105, Number = 105, Traduction = "ONE HUNDRED FIVE" },
                new Numbers { IdNumber = 106, Number = 106, Traduction = "ONE HUNDRED SIX" },
                new Numbers { IdNumber = 107, Number = 107, Traduction = "ONE HUNDRED SEVEN" },
                new Numbers { IdNumber = 108, Number = 108, Traduction = "ONE HUNDRED EIGHT" },
                new Numbers { IdNumber = 109, Number = 109, Traduction = "ONE HUNDRED NINE" },
                new Numbers { IdNumber = 110, Number = 110, Traduction = "ONE HUNDRED TEN" },
                new Numbers { IdNumber = 111, Number = 111, Traduction = "ONE HUNDRED ELEVEN" },
                new Numbers { IdNumber = 112, Number = 112, Traduction = "ONE HUNDRED TWELVE" },
                new Numbers { IdNumber = 113, Number = 113, Traduction = "ONE HUNDRED THIRTEEN" },
                new Numbers { IdNumber = 114, Number = 114, Traduction = "ONE HUNDRED FOURTEEN" },
                new Numbers { IdNumber = 115, Number = 115, Traduction = "ONE HUNDRED FIFTEEN" },
                new Numbers { IdNumber = 116, Number = 116, Traduction = "ONE HUNDRED SIXTEEN" },
                new Numbers { IdNumber = 117, Number = 117, Traduction = "ONE HUNDRED SEVENTEEN" },
                new Numbers { IdNumber = 118, Number = 118, Traduction = "ONE HUNDRED EIGHTEEN" },
                new Numbers { IdNumber = 119, Number = 119, Traduction = "ONE HUNDRED NINETEEN" },
                new Numbers { IdNumber = 120, Number = 120, Traduction = "ONE HUNDRED TWENTY" },
                new Numbers { IdNumber = 121, Number = 121, Traduction = "ONE HUNDRED TWENTY ONE" },
                new Numbers { IdNumber = 122, Number = 122, Traduction = "ONE HUNDRED TWENTY TWO" },
                new Numbers { IdNumber = 123, Number = 123, Traduction = "ONE HUNDRED TWENTY THREE" },
                new Numbers { IdNumber = 124, Number = 124, Traduction = "ONE HUNDRED TWENTY FOUR" },
                new Numbers { IdNumber = 125, Number = 125, Traduction = "ONE HUNDRED TWENTY FIVE" },
                new Numbers { IdNumber = 126, Number = 126, Traduction = "ONE HUNDRED TWENTY SIX" },
                new Numbers { IdNumber = 127, Number = 127, Traduction = "ONE HUNDRED TWENTY SEVEN" },
                new Numbers { IdNumber = 128, Number = 128, Traduction = "ONE HUNDRED TWENTY EIGHT" },
                new Numbers { IdNumber = 129, Number = 129, Traduction = "ONE HUNDRED TWENTY NINE" },
                new Numbers { IdNumber = 130, Number = 130, Traduction = "ONE HUNDRED THIRTY" },
                new Numbers { IdNumber = 131, Number = 131, Traduction = "ONE HUNDRED THIRTY ONE" },
                new Numbers { IdNumber = 132, Number = 132, Traduction = "ONE HUNDRED THIRTY TWO" },
                new Numbers { IdNumber = 133, Number = 133, Traduction = "ONE HUNDRED THIRTY THREE" },
                new Numbers { IdNumber = 134, Number = 134, Traduction = "ONE HUNDRED THIRTY FOUR" },
                new Numbers { IdNumber = 135, Number = 135, Traduction = "ONE HUNDRED THIRTY FIVE" },
                new Numbers { IdNumber = 136, Number = 136, Traduction = "ONE HUNDRED THIRTY SIX" },
                new Numbers { IdNumber = 137, Number = 137, Traduction = "ONE HUNDRED THIRTY SEVEN" },
                new Numbers { IdNumber = 138, Number = 138, Traduction = "ONE HUNDRED THIRTY EIGHT" },
                new Numbers { IdNumber = 139, Number = 139, Traduction = "ONE HUNDRED THIRTY NINE" },
                new Numbers { IdNumber = 140, Number = 140, Traduction = "ONE HUNDRED FORTY" },
                new Numbers { IdNumber = 141, Number = 141, Traduction = "ONE HUNDRED FORTY ONE" },
                new Numbers { IdNumber = 142, Number = 142, Traduction = "ONE HUNDRED FORTY TWO" },
                new Numbers { IdNumber = 143, Number = 143, Traduction = "ONE HUNDRED FORTY THREE" },
                new Numbers { IdNumber = 144, Number = 144, Traduction = "ONE HUNDRED FORTY FOUR" },
                new Numbers { IdNumber = 145, Number = 145, Traduction = "ONE HUNDRED FORTY FIVE" },
                new Numbers { IdNumber = 146, Number = 146, Traduction = "ONE HUNDRED FORTY SIX" },
                new Numbers { IdNumber = 147, Number = 147, Traduction = "ONE HUNDRED FORTY SEVEN" },
                new Numbers { IdNumber = 148, Number = 148, Traduction = "ONE HUNDRED FORTY EIGHT" },
                new Numbers { IdNumber = 149, Number = 149, Traduction = "ONE HUNDRED FORTY NINE" },
                new Numbers { IdNumber = 150, Number = 150, Traduction = "ONE HUNDRED FIFTY" },
                new Numbers { IdNumber = 151, Number = 151, Traduction = "ONE HUNDRED FIFTY ONE" },
                new Numbers { IdNumber = 152, Number = 152, Traduction = "ONE HUNDRED FIFTY TWO" },
                new Numbers { IdNumber = 153, Number = 153, Traduction = "ONE HUNDRED FIFTY THREE" },
                new Numbers { IdNumber = 154, Number = 154, Traduction = "ONE HUNDRED FIFTY FOUR" },
                new Numbers { IdNumber = 155, Number = 155, Traduction = "ONE HUNDRED FIFTY FIVE" },
                new Numbers { IdNumber = 156, Number = 156, Traduction = "ONE HUNDRED FIFTY SIX" },
                new Numbers { IdNumber = 157, Number = 157, Traduction = "ONE HUNDRED FIFTY SEVEN" },
                new Numbers { IdNumber = 158, Number = 158, Traduction = "ONE HUNDRED FIFTY EIGHT" },
                new Numbers { IdNumber = 159, Number = 159, Traduction = "ONE HUNDRED FIFTY NINE" },
                new Numbers { IdNumber = 160, Number = 160, Traduction = "ONE HUNDRED SIXTY" },
                new Numbers { IdNumber = 161, Number = 161, Traduction = "ONE HUNDRED SIXTY ONE" },
                new Numbers { IdNumber = 162, Number = 162, Traduction = "ONE HUNDRED SIXTY TWO" },
                new Numbers { IdNumber = 163, Number = 163, Traduction = "ONE HUNDRED SIXTY THREE" },
                new Numbers { IdNumber = 164, Number = 164, Traduction = "ONE HUNDRED SIXTY FOUR" },
                new Numbers { IdNumber = 165, Number = 165, Traduction = "ONE HUNDRED SIXTY FIVE" },
                new Numbers { IdNumber = 166, Number = 166, Traduction = "ONE HUNDRED SIXTY SIX" },
                new Numbers { IdNumber = 167, Number = 167, Traduction = "ONE HUNDRED SIXTY SEVEN" },
                new Numbers { IdNumber = 168, Number = 168, Traduction = "ONE HUNDRED SIXTY EIGHT" },
                new Numbers { IdNumber = 169, Number = 169, Traduction = "ONE HUNDRED SIXTY NINE" },
                new Numbers { IdNumber = 170, Number = 170, Traduction = "ONE HUNDRED SEVENTY" },
                new Numbers { IdNumber = 171, Number = 171, Traduction = "ONE HUNDRED SEVENTY ONE" },
                new Numbers { IdNumber = 172, Number = 172, Traduction = "ONE HUNDRED SEVENTY TWO" },
                new Numbers { IdNumber = 173, Number = 173, Traduction = "ONE HUNDRED SEVENTY THREE" },
                new Numbers { IdNumber = 174, Number = 174, Traduction = "ONE HUNDRED SEVENTY FOUR" },
                new Numbers { IdNumber = 175, Number = 175, Traduction = "ONE HUNDRED SEVENTY FIVE" },
                new Numbers { IdNumber = 176, Number = 176, Traduction = "ONE HUNDRED SEVENTY SIX" },
                new Numbers { IdNumber = 177, Number = 177, Traduction = "ONE HUNDRED SEVENTY SEVEN" },
                new Numbers { IdNumber = 178, Number = 178, Traduction = "ONE HUNDRED SEVENTY EIGHT" },
                new Numbers { IdNumber = 179, Number = 179, Traduction = "ONE HUNDRED SEVENTY NINE" },
                new Numbers { IdNumber = 180, Number = 180, Traduction = "ONE HUNDRED EIGHTY" },
                new Numbers { IdNumber = 181, Number = 181, Traduction = "ONE HUNDRED EIGHTY ONE" },
                new Numbers { IdNumber = 182, Number = 182, Traduction = "ONE HUNDRED EIGHTY TWO" },
                new Numbers { IdNumber = 183, Number = 183, Traduction = "ONE HUNDRED EIGHTY THREE" },
                new Numbers { IdNumber = 184, Number = 184, Traduction = "ONE HUNDRED EIGHTY FOUR" },
                new Numbers { IdNumber = 185, Number = 185, Traduction = "ONE HUNDRED EIGHTY FIVE" },
                new Numbers { IdNumber = 186, Number = 186, Traduction = "ONE HUNDRED EIGHTY SIX" },
                new Numbers { IdNumber = 187, Number = 187, Traduction = "ONE HUNDRED EIGHTY SEVEN" },
                new Numbers { IdNumber = 188, Number = 188, Traduction = "ONE HUNDRED EIGHTY EIGHT" },
                new Numbers { IdNumber = 189, Number = 189, Traduction = "ONE HUNDRED EIGHTY NINE" },
                new Numbers { IdNumber = 190, Number = 190, Traduction = "ONE HUNDRED NINETY" },
                new Numbers { IdNumber = 191, Number = 191, Traduction = "ONE HUNDRED EIGHTY ONE" },
                new Numbers { IdNumber = 192, Number = 192, Traduction = "ONE HUNDRED NINETY TWO" },
                new Numbers { IdNumber = 193, Number = 193, Traduction = "ONE HUNDRED NINETY THREE" },
                new Numbers { IdNumber = 194, Number = 194, Traduction = "ONE HUNDRED NINETY FOUR" },
                new Numbers { IdNumber = 195, Number = 195, Traduction = "ONE HUNDRED NINETY FIVE" },
                new Numbers { IdNumber = 196, Number = 196, Traduction = "ONE HUNDRED NINETY SIX" },
                new Numbers { IdNumber = 197, Number = 197, Traduction = "ONE HUNDRED NINETY SEVEN" },
                new Numbers { IdNumber = 198, Number = 198, Traduction = "ONE HUNDRED NINETY EIGHT" },
                new Numbers { IdNumber = 199, Number = 199, Traduction = "ONE HUNDRED NINETY NINE" },
                new Numbers { IdNumber = 200, Number = 200, Traduction = "TWO HUNDRED" },
            };

            _dbCcontext.AddRange(numbers);
            _dbCcontext.SaveChanges();
        }
    }
}